# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
     # Uncommentable files
     ".gitignore",
     "tests/audio/*",
     "VERSION",
     # Computer-generated files.
     "tests/nml/test.nml",
     "tests/rb7xml/rbxml_test.xml",
     "flake.lock",
     ".github/workflows/build.yml",
     "tests/subcrates/crate_write_test.crate",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"