name: Test, Build and Release

on:
  push:
    tags:
      - 'v*'  # Only on version tags like v1.0.0

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Run tests
        run: |
          hatch test


  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    needs: test  # Only run docs after tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Build HTML docs with Sphinx
        working-directory: ./doc
        run: hatch run docs:make html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/_build/html


  deploy-pages:
    name: Deploy Docs to Pages
    runs-on: ubuntu-latest
    needs: docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            suffix: linux
          - os: windows-latest
            suffix: win
          - os: macos-latest
            suffix: mac

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Build executable
        env:
          PYINSTALLER_NAME: djbabel-${{ matrix.suffix }}
        run: |
          hatch run build:build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.suffix }}-binary
          path: dist/*


  release:
    # if: false # skip during tests
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, deploy-pages]

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
